config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :ad_accounts

  resources :projects

  resources :clients

  resources :ad_categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/ad_account.rb
class AdAccount < ActiveRecord::Base
  belongs_to :client
end

app/controllers/ad_accounts_controller.rb
class AdAccountsController < ApplicationController
  before_action :set_ad_account, only: [:show, :edit, :update, :destroy]

  # GET /ad_accounts
  # GET /ad_accounts.json
  def index
    @ad_accounts = AdAccount.all
  end

  # GET /ad_accounts/1
  # GET /ad_accounts/1.json
  def show
  end

  # GET /ad_accounts/new
  def new
    @ad_account = AdAccount.new
  end

  # GET /ad_accounts/1/edit
  def edit
  end

  # POST /ad_accounts
  # POST /ad_accounts.json
  def create
    @ad_account = AdAccount.new(ad_account_params)

    respond_to do |format|
      if @ad_account.save
        format.html { redirect_to @ad_account, notice: 'Ad account was successfully created.' }
        format.json { render :show, status: :created, location: @ad_account }
      else
        format.html { render :new }
        format.json { render json: @ad_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ad_accounts/1
  # PATCH/PUT /ad_accounts/1.json
  def update
    respond_to do |format|
      if @ad_account.update(ad_account_params)
        format.html { redirect_to @ad_account, notice: 'Ad account was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad_account }
      else
        format.html { render :edit }
        format.json { render json: @ad_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_accounts/1
  # DELETE /ad_accounts/1.json
  def destroy
    @ad_account.destroy
    respond_to do |format|
      format.html { redirect_to ad_accounts_url, notice: 'Ad account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad_account
      @ad_account = AdAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_account_params
      params.require(:ad_account).permit(:email, :phone, :login, :token, :data, :client_id, :deleted_at)
    end
end

app/helpers/ad_accounts_helper.rb
module AdAccountsHelper
end

app/views/ad_accounts/_form.html.erb
<%= form_for @ad_account, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :login, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :login, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :token, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :token, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :data, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deleted_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :deleted_at, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ad_accounts_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ad_accounts/edit.html.erb
<%- model_class = AdAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => AdAccount %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ad_accounts/index.html.erb
<%- model_class = AdAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => AdAccount %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:login) %></th>
      <th><%= model_class.human_attribute_name(:token) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:deleted_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ad_accounts.each do |ad_account| %>
      <tr>
        <td><%= ad_account.id %></td>
        <td><%= ad_account.email %></td>
        <td><%= ad_account.phone %></td>
        <td><%= ad_account.login %></td>
        <td><%= ad_account.token %></td>
        <td><%= ad_account.data %></td>
        <td><%= ad_account.deleted_at %></td>
        <td><%=l ad_account.created_at, format: :long %></td>
        <td>
          <%= link_to ad_account_path(ad_account), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to ad_account_path(ad_account), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ad_account_path,
            :class => 'btn btn-primary' %>

app/views/ad_accounts/new.html.erb
<%- model_class = AdAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => AdAccount %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ad_accounts/show.html.erb
<%- model_class = AdAccount -%>
<div class="page-header">
  <h1><%=t '.title', :default => AdAccount %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @ad_account.email %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @ad_account.phone %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:login) %></dt>
      <dd><pre class="prettyprint"><%= @ad_account.login %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:token) %></dt>
      <dd><pre class="prettyprint"><%= @ad_account.token %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:data) %></dt>
      <dd><pre class="prettyprint"><%= @ad_account.data %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:deleted_at) %></dt>
      <dd><pre class="prettyprint"><%= @ad_account.deleted_at %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ad_accounts_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ad_account_path(@ad_account), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ad_account_path(@ad_account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>