config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :ad_accounts

  resources :projects

  resources :clients

  resources :ad_categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/ad_category.rb
class AdCategory < ActiveRecord::Base
  belongs_to :client
end

app/controllers/ad_categories_controller.rb
class AdCategoriesController < ApplicationController
  before_action :set_ad_category, only: [:show, :edit, :update, :destroy]

  # GET /ad_categories
  # GET /ad_categories.json
  def index
    @ad_categories = AdCategory.all
  end

  # GET /ad_categories/1
  # GET /ad_categories/1.json
  def show
  end

  # GET /ad_categories/new
  def new
    @ad_category = AdCategory.new
  end

  # GET /ad_categories/1/edit
  def edit
  end

  # POST /ad_categories
  # POST /ad_categories.json
  def create
    @ad_category = AdCategory.new(ad_category_params)

    respond_to do |format|
      if @ad_category.save
        format.html { redirect_to @ad_category, notice: 'Ad category was successfully created.' }
        format.json { render :show, status: :created, location: @ad_category }
      else
        format.html { render :new }
        format.json { render json: @ad_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ad_categories/1
  # PATCH/PUT /ad_categories/1.json
  def update
    respond_to do |format|
      if @ad_category.update(ad_category_params)
        format.html { redirect_to @ad_category, notice: 'Ad category was successfully updated.' }
        format.json { render :show, status: :ok, location: @ad_category }
      else
        format.html { render :edit }
        format.json { render json: @ad_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_categories/1
  # DELETE /ad_categories/1.json
  def destroy
    @ad_category.destroy
    respond_to do |format|
      format.html { redirect_to ad_categories_url, notice: 'Ad category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad_category
      @ad_category = AdCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_category_params
      params.require(:ad_category).permit(:name, :url, :title, :ad_texts, :fast_urls, :client_id, :deleted_at, :ad_text1, :ad_text2, :ad_text3, :ad_text4, :ad_text5, :fast_url1, :fast_url2, :fast_url3, :fast_url4, :fast_url_title1, :fast_url_title2, :fast_url_title3, :fast_url_title4)
    end
end

app/helpers/ad_categories_helper.rb
module AdCategoriesHelper
end

app/views/ad_categories/_form.html.erb
<%= form_for @ad_category, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :url, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ad_texts, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ad_texts, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_urls, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_urls, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deleted_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :deleted_at, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ad_text1, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ad_text1, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ad_text2, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ad_text2, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ad_text3, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ad_text3, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ad_text4, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ad_text4, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ad_text5, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :ad_text5, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url1, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url1, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url2, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url2, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url3, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url3, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url4, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url4, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url_title1, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url_title1, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url_title2, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url_title2, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url_title3, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url_title3, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fast_url_title4, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :fast_url_title4, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  ad_categories_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/ad_categories/edit.html.erb
<%- model_class = AdCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => AdCategory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ad_categories/index.html.erb
<%- model_class = AdCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => AdCategory %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:ad_texts) %></th>
      <th><%= model_class.human_attribute_name(:fast_urls) %></th>
      <th><%= model_class.human_attribute_name(:deleted_at) %></th>
      <th><%= model_class.human_attribute_name(:ad_text1) %></th>
      <th><%= model_class.human_attribute_name(:ad_text2) %></th>
      <th><%= model_class.human_attribute_name(:ad_text3) %></th>
      <th><%= model_class.human_attribute_name(:ad_text4) %></th>
      <th><%= model_class.human_attribute_name(:ad_text5) %></th>
      <th><%= model_class.human_attribute_name(:fast_url1) %></th>
      <th><%= model_class.human_attribute_name(:fast_url2) %></th>
      <th><%= model_class.human_attribute_name(:fast_url3) %></th>
      <th><%= model_class.human_attribute_name(:fast_url4) %></th>
      <th><%= model_class.human_attribute_name(:fast_url_title1) %></th>
      <th><%= model_class.human_attribute_name(:fast_url_title2) %></th>
      <th><%= model_class.human_attribute_name(:fast_url_title3) %></th>
      <th><%= model_class.human_attribute_name(:fast_url_title4) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ad_categories.each do |ad_category| %>
      <tr>
        <td><%= ad_category.id %></td>
        <td><%= ad_category.name %></td>
        <td><%= ad_category.url %></td>
        <td><%= ad_category.title %></td>
        <td><%= ad_category.ad_texts %></td>
        <td><%= ad_category.fast_urls %></td>
        <td><%= ad_category.deleted_at %></td>
        <td><%= ad_category.ad_text1 %></td>
        <td><%= ad_category.ad_text2 %></td>
        <td><%= ad_category.ad_text3 %></td>
        <td><%= ad_category.ad_text4 %></td>
        <td><%= ad_category.ad_text5 %></td>
        <td><%= ad_category.fast_url1 %></td>
        <td><%= ad_category.fast_url2 %></td>
        <td><%= ad_category.fast_url3 %></td>
        <td><%= ad_category.fast_url4 %></td>
        <td><%= ad_category.fast_url_title1 %></td>
        <td><%= ad_category.fast_url_title2 %></td>
        <td><%= ad_category.fast_url_title3 %></td>
        <td><%= ad_category.fast_url_title4 %></td>
        <td><%=l ad_category.created_at, format: :long %></td>
        <td>
          <%= link_to ad_category_path(ad_category), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to ad_category_path(ad_category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_ad_category_path,
            :class => 'btn btn-primary' %>

app/views/ad_categories/new.html.erb
<%- model_class = AdCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => AdCategory %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ad_categories/show.html.erb
<%- model_class = AdCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => AdCategory %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:url) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.url %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ad_texts) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.ad_texts %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_urls) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_urls %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:deleted_at) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.deleted_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ad_text1) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.ad_text1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ad_text2) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.ad_text2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ad_text3) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.ad_text3 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ad_text4) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.ad_text4 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ad_text5) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.ad_text5 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url1) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url2) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url3) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url3 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url4) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url4 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url_title1) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url_title1 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url_title2) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url_title2 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url_title3) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url_title3 %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:fast_url_title4) %></dt>
      <dd><pre class="prettyprint"><%= @ad_category.fast_url_title4 %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              ad_categories_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_ad_category_path(@ad_category), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              ad_category_path(@ad_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>