config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :ad_accounts

  resources :projects

  resources :clients

  resources :ad_categories

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :users
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.user = current_user

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:user_id, :name, :state_id, :phone, :data, :legal_form, :legal_name, :legal_inn, :legal_kpp, :legal_ogrn, :legal_address, :post_address, :legal_bank_name, :legal_bank_bic, :legal_cor_acc_num, :legal_bank_acc_num, :legal_ceo_reason, :legal_ceo_position, :legal_ceo_full_name, :deleted_at, :balance, :web_site)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :state_id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :phone, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :data, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :data, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_form, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_form, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_inn, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_inn, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_kpp, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_kpp, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_ogrn, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_ogrn, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :post_address, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :post_address, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_bank_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_bank_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_bank_bic, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_bank_bic, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_cor_acc_num, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_cor_acc_num, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_bank_acc_num, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_bank_acc_num, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_ceo_reason, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_ceo_reason, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_ceo_position, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_ceo_position, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :legal_ceo_full_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :legal_ceo_full_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deleted_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :deleted_at, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :balance, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :balance, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :web_site, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :web_site, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  clients_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Client %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/index.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => Client %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:state_id) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:legal_form) %></th>
      <th><%= model_class.human_attribute_name(:legal_name) %></th>
      <th><%= model_class.human_attribute_name(:legal_inn) %></th>
      <th><%= model_class.human_attribute_name(:legal_kpp) %></th>
      <th><%= model_class.human_attribute_name(:legal_ogrn) %></th>
      <th><%= model_class.human_attribute_name(:legal_address) %></th>
      <th><%= model_class.human_attribute_name(:post_address) %></th>
      <th><%= model_class.human_attribute_name(:legal_bank_name) %></th>
      <th><%= model_class.human_attribute_name(:legal_bank_bic) %></th>
      <th><%= model_class.human_attribute_name(:legal_cor_acc_num) %></th>
      <th><%= model_class.human_attribute_name(:legal_bank_acc_num) %></th>
      <th><%= model_class.human_attribute_name(:legal_ceo_reason) %></th>
      <th><%= model_class.human_attribute_name(:legal_ceo_position) %></th>
      <th><%= model_class.human_attribute_name(:legal_ceo_full_name) %></th>
      <th><%= model_class.human_attribute_name(:deleted_at) %></th>
      <th><%= model_class.human_attribute_name(:balance) %></th>
      <th><%= model_class.human_attribute_name(:web_site) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.id %></td>
        <td><%= client.name %></td>
        <td><%= client.state_id %></td>
        <td><%= client.phone %></td>
        <td><%= client.data %></td>
        <td><%= client.legal_form %></td>
        <td><%= client.legal_name %></td>
        <td><%= client.legal_inn %></td>
        <td><%= client.legal_kpp %></td>
        <td><%= client.legal_ogrn %></td>
        <td><%= client.legal_address %></td>
        <td><%= client.post_address %></td>
        <td><%= client.legal_bank_name %></td>
        <td><%= client.legal_bank_bic %></td>
        <td><%= client.legal_cor_acc_num %></td>
        <td><%= client.legal_bank_acc_num %></td>
        <td><%= client.legal_ceo_reason %></td>
        <td><%= client.legal_ceo_position %></td>
        <td><%= client.legal_ceo_full_name %></td>
        <td><%= client.deleted_at %></td>
        <td><%= client.balance %></td>
        <td><%= client.web_site %></td>
        <td><%=l client.created_at, format: :long %></td>
        <td>
          <%= link_to client_path(client), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to client_path(client), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_client_path,
            :class => 'btn btn-primary' %>

app/views/clients/new.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Client %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clients/show.html.erb
<%- model_class = Client -%>
<div class="page-header">
  <h1><%=t '.title', :default => Client %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @client.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:state_id) %></dt>
      <dd><pre class="prettyprint"><%= @client.state_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:phone) %></dt>
      <dd><pre class="prettyprint"><%= @client.phone %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:data) %></dt>
      <dd><pre class="prettyprint"><%= @client.data %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_form) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_form %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_name) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_inn) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_inn %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_kpp) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_kpp %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_ogrn) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_ogrn %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_address) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:post_address) %></dt>
      <dd><pre class="prettyprint"><%= @client.post_address %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_bank_name) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_bank_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_bank_bic) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_bank_bic %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_cor_acc_num) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_cor_acc_num %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_bank_acc_num) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_bank_acc_num %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_ceo_reason) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_ceo_reason %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_ceo_position) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_ceo_position %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:legal_ceo_full_name) %></dt>
      <dd><pre class="prettyprint"><%= @client.legal_ceo_full_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:deleted_at) %></dt>
      <dd><pre class="prettyprint"><%= @client.deleted_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:balance) %></dt>
      <dd><pre class="prettyprint"><%= @client.balance %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:web_site) %></dt>
      <dd><pre class="prettyprint"><%= @client.web_site %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              clients_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_client_path(@client), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              client_path(@client),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>